version: '3'
services:
  nginx:
    build:
      context: ./docker
      dockerfile: nginx.docker
    volumes:
      - ./:/var/www
      - ./docker/nginx/ssl:/etc/nginx/ssl
    ports:
      - "443:443"
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./docker
      dockerfile: php-fpm.docker
    volumes:
      - ./:/var/www
    depends_on:
      - postgres
      - redis
    environment:
      - "DB_PORT=5432"
      - "DB_HOST=postgres"
      - "REDIS_PORT=6379"
      - "REDIS_HOST=redis"
  php-cli:
    build:
      context: ./docker
      dockerfile: php-cli.docker
    volumes:
      - ./:/var/www
    depends_on:
      - postgres
      - redis
    environment:
      - "DB_PORT=5432"
      - "DB_HOST=postgres"
      - "REDIS_PORT=6379"
      - "REDIS_HOST=redis"
    working_dir: /var/www
    tty: true

  postgres:
    image: postgres:11.2-alpine
    volumes:
      - manager-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    ports:
      - "54321:5432"

  nodejs:
    image: node:10.11-jessie
    volumes:
      - ./:/var/www
    working_dir: /var/www
    tty: true

  redis:
    image: redis:3.0
    ports:
      - "63791:6379"

  mailer:
    image: mailhog/mailhog
    ports:
      - "8082:8025"

volumes:
  manager-postgres:
  manager-redis:
  manager-queue-redis:
  composer: